<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>blood-donation.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="blood-donation.ico" />
    <None Remove="BloodData.json" />
    <None Remove="BloodStorageReport2.rdlc" />
    <None Remove="SupReport.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.19" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.19" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
    <PackageReference Include="ToastNotifications" Version="2.5.1" />
    <PackageReference Include="ToastNotifications.Messages" Version="2.5.1" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="WindowsFormsIntegration">
		  <HintPath>..\..\..\..\..\..\Program Files\Reference Assemblies\Microsoft\Framework\v3.0\WindowsFormsIntegration.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.30\analyzers\dotnet\System.Windows.Forms.Analyzers.dll" />
		<Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.30\analyzers\dotnet\cs\System.Windows.Forms.Analyzers.CSharp.dll" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="blood-donation.ico" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="blood-donation.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="BloodStorageReport2.rdlc">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="SupReport.rdlc">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="BloodData.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="BloodStorageDataset.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>BloodStorageDataset.xsd</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="App.config">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="BloodStorageDataset.xsd">
	    <Generator>MSDataSetGenerator</Generator>
	    <LastGenOutput>BloodStorageDataset.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

</Project>
